version: '3.7'

services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create-multiple-postgres-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgres-databases.sh
    ports:
      - 5432:5432
    environment:
      # - POSTGRES_DB=postgres
      - POSTGRES_USER=football
      - POSTGRES_PASSWORD=football
      - POSTGRES_MULTIPLE_DATABASES=app,mlflow
    # container_name: postgres_db
    networks:
      - football

  web:
    build:
       context: .
       dockerfile: Dockerfile
    volumes:
      - static:/app/static
      - ./football_analysis_app:/app/
      - ./Backups:/app/Backups
      - mlflow-artifact-store:/opt/mlflow/mlruns
    env_file:
      - .env
    ports:
      - "8000:8000"
    mem_limit: 800m
    cpus: 0.5
    depends_on:
      - db
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-tracking-service:5000
      - POSTGRES_USER=football
      - POSTGRES_PASSWORD=football
    restart: always
    networks:
      - football

  djangojobs:
    build:
       context: .
       dockerfile: Dockerfile.jobs
    volumes:
      - static:/app/static
      - ./football_analysis_app:/app/
      - mlflow-artifact-store:/opt/mlflow/mlruns
    env_file:
      - .env
    depends_on:
      - db
    mem_limit: 800m
    cpus: 0.75
    restart: always
    networks:
      - football

  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - football

  mlflow-tracking-service:
    depends_on:
      - web
    environment:
      - MLFLOW_TRACKING_URI=postgresql://football:football@db:5432/mlflow
    image: mlflow-tracking-server
    networks:
      - football
    ports:
      - 5000:5000
    volumes:
      - mlflow-artifact-store:/opt/mlflow/mlruns
    profiles:
      - ml

  datascience-notebook:
    image: jupyter-notebook
    #build:
    #  context: .
    #  dockerfile: Dockerfile.jupyter
    volumes:
      - ./jupyter-notebooks:/home/jovyan/work
      - mlflow-artifact-store:/opt/mlflow/mlruns
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=ADMIN
      - MLFLOW_TRACKING_URI=http://mlflow-tracking-service:5000
    networks:
      - football
    profiles:
      - ml

volumes:
  static:
  pgdata:
    driver: local
  mlflow-artifact-store:
    driver: local
  football_analysis_app:
    driver: local

networks:
  football:
    name: football
