version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  web:
    image: fred031/football-app:app_0.0.1
    volumes:
      - static:/app/static
      - ./football_analysis_app/:/app/
      - ./Backups/:/app/Backups
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  djangojobs:
    image: fred031/football-app:jobs_0.0.1
    volumes:
      - static:/app/static
      - ./football_analysis_app/:/app/
    env_file:
      - .env
    depends_on:
      - db
    mem_limit: 800m
    restart: always
    
  nginx:
    image: football-analysis-app-infrastructure_nginx
    volumes:
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
    
    

volumes:
  static:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local


