version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  web:
    volumes:
      - static:/app/static
      - ./football_analysis_app/:/app/
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  djangojobs:
    volumes:
      - static:/app/static
      - ./football_analysis_app/:/app/
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.jobs
    depends_on:
      - db
    
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local


